Menambahkan pustaka nama-gadungan
frontend-id/oss pull request #14
Opened 2020-09-24 02:10 UTC by rizafahmi

2020-09-24 02:13 UTC, angeloanan commented
Hi, tolong diuruti kembali itemnya agar listnya terurut secara alphabetis ya!

2020-09-24 02:15 UTC, angeloanan requested changes
Tolong pindahkan itemnya keatas agar listnya dapat terurut secara alphabetis, ya

2020-09-24 10:35 UTC, rizafahmi commented
Baiklah. Sudah dipindahkan

2020-09-24 11:04 UTC, jefrydco approved these changes

2020-09-24 11:05 UTC, jefrydco commented
Saya bantu resolve conflictnya Mas @rizafahmi

2020-09-24 11:05 UTC, merged

2020-09-25 03:05 UTC, rizafahmi commented
Wah, ada conflict ya? Kok ngga sadar. Terimakasih @jefrydco 🙇