adding QRious Javascript library
frontend-id/oss pull request #23
Opened 2020-10-01 11:42 UTC by dodycode

2020-10-01 12:48 UTC, jefrydco requested changes
Minta tolong tambah format `keyword` nya ya

2020-10-02 07:06 UTC, dodycode commented
Oops mohon maaf, silahkan di cek kembali ya mas @jefrydco

2020-10-02 07:17 UTC, jefrydco commented on README-ID.md
> +- [QRious](https://github.com/neocotic/qrious) oleh [neocotic](https://github.com/neocotic) - Library murni Javascript yang di ciptakan untuk pembuatan QR Code menggunakan HTML Canvas - qr, qrcode, q
`Library` mungkin bisa dipadankan dengan `Pustaka`

2020-10-02 08:04 UTC, dodycode commented on README-ID.md
> +- [QRious](https://github.com/neocotic/qrious) oleh [neocotic](https://github.com/neocotic) - Library murni Javascript yang di ciptakan untuk pembuatan QR Code menggunakan HTML Canvas - qr, qrcode, q
Oke silahkan di cek kembali ya mas @jefrydco

2020-10-02 09:13 UTC, jefrydco approved these changes
Thank you!

2020-10-02 09:14 UTC, merged