add pantaucovid website to list
frontend-id/oss pull request #33
Opened 2021-02-10 16:49 UTC by fiqryq

2021-02-10 17:35 UTC, resir014 requested changes

2021-02-10 17:35 UTC, resir014 commented on README.md
> +- [Situs web pantaucovidapp.netlify.app](https://github.com/fiqryq/Pantaucovid-Dashboard) oleh [Fiqry choerudin](https://github.com/fiqryq) - Vue.js
```suggestion
- [pantaucovidapp.netlify.app website](https://github.com/fiqryq/Pantaucovid-Dashboard) by [Fiqry choerudin](https://github.com/fiqryq) - Vue.js
```

Untuk `README.md` gunakan bahasa Inggris ya.

2021-02-11 03:17 UTC, fiqryq reviewed
done

2021-02-15 11:48 UTC, resir014 approved these changes

2021-02-15 11:48 UTC, merged